#!/bin/bash
set -e

psql -U postgres << EOF
CREATE ROLE ${KANTELE_ROLE} WITH LOGIN PASSWORD '${KANTELE_PASSWORD}';
ALTER USER ${KANTELE_ROLE} CREATEDB;
CREATE DATABASE ${KANTELE_DB} OWNER ${KANTELE_ROLE};
GRANT ALL ON SCHEMA public TO ${KANTELE_ROLE};
ALTER SCHEMA public OWNER TO ${KANTELE_ROLE};
EOF
