# For running scanheadsman in a dotnet docker
# Got code from Filip @ Lund
# Also has NF procps and gettext-base so it will be possible to run inside NF pipelines
FROM debian:bookworm-slim
RUN apt-get update -y && apt-get install -y --no-install-recommends gettext-base procps unzip ca-certificates
ADD https://packages.microsoft.com/config/debian/13/packages-microsoft-prod.deb packages-microsoft-prod.deb
RUN dpkg -i packages-microsoft-prod.deb && rm packages-microsoft-prod.deb
RUN apt-get update -y && apt-get install -y aspnetcore-runtime-8.0 dotnet-runtime-8.0

ADD https://github.com/CompOmics/ThermoRawFileParser/releases/download/v.2.0.0-dev/ThermoRawFileParser-v.2.0.0-dev-linux.zip /thermofp.zip
RUN unzip /thermofp.zip -d /usr/local/thermorawfileparser
RUN chmod 755 -R /usr/local && apt-get clean && rm -rf /var/lib/apt/lists/* && rm -rf ./*.zip

ADD https://bitbucket.org/caetera/scanheadsman/downloads/ScanHeadsman-1.4.20260310.zip /scanheadsman.zip
RUN mkdir /scanheadsman && cd /scanheadsman && unzip /scanheadsman.zip
WORKDIR /scanheadsman
