# Generated by Django 5.2 on 2025-07-03 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0054_alter_psetcomponent_component'),
        ('rawstatus', '0036_remove_filejob_storedfile_remove_servershare_server_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresultfile',
            name='sfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawstatus.storedfile'),
        ),
    ]
