# Generated by Django 5.2 on 2025-10-07 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0055_alter_analysisresultfile_sfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nextflowwfversionparamset',
            name='profiles',
        ),
        migrations.RemoveField(
            model_name='proteowizard',
            name='is_docker',
        ),
    ]
