# Generated by Django 5.2 on 2025-10-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0056_remove_nextflowwfversionparamset_profiles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proteowizard',
            name='container_version',
        ),
        migrations.AddField(
            model_name='proteowizard',
            name='params',
            field=models.JSONField(blank=True, default=dict, help_text='E.g. {"centroid": "1,2", "mzmltool": "msconvert"}'),
        ),
    ]
