# Generated by Django 5.2 on 2025-10-28 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0057_remove_proteowizard_container_version_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysis',
            old_name='storage_dir',
            new_name='base_rundir',
        ),
    ]
