# Generated by Django 5.2 on 2025-11-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0058_rename_storage_dir_analysis_base_rundir'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='securityclass',
            field=models.IntegerField(choices=[(1, 'Accessible')], default=1),
            preserve_default=False,
        ),
    ]
