# Generated by Django 5.2 on 2026-01-13 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0060_alter_psetcomponent_component'),
        ('rawstatus', '0042_remove_analysisserverprofile_nfprofiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='NfConfigFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nfconfig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.libraryfile')),
                ('nfpipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.nextflowwfversionparamset')),
                ('serverprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawstatus.analysisserverprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('serverprofile', 'nfpipe', 'nfconfig'), name='uni_nfconfigfile')],
            },
        ),
    ]
