# Generated by Django 5.2 on 2026-01-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0061_nfconfigfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisdeleted',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
