# Generated by Django 5.2 on 2026-03-04 14:42

from django.db import migrations, models
from jobs import jobs as jj


def fake(x, y):
    pass

def fixfield(apps, s):
    A = apps.get_model('analysis', 'Analysis')
    A.objects.filter(nextflowsearch__job__state=jj.Jobstates.DONE).update(success_completed=True)


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0062_alter_analysisdeleted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='success_completed',
            field=models.BooleanField(default=False),
        ),

        migrations.RunPython(fixfield, fake)
    ]
