# Generated by Django 5.2 on 2026-05-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0063_analysis_success_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psetcomponent',
            name='value',
            field=models.JSONField(default=dict, help_text='JSON, e.g. [path, instrument, set, plate] (path must be first),\n            {rawfile: __path, field_w_default: 1, file_type: "**function"}, empty_field: False}'),
        ),
    ]
