# Generated by Django 5.2 on 2026-05-08 09:49

import django.db.models.deletion
from django.db import migrations, models


def nfwfver_to_repo(apps, s):
    Nfwfver = apps.get_model('analysis', 'NextflowWfVersionParamset')
    NfConfigfile = apps.get_model('analysis', 'NfConfigfile')
    ver_to_repo = {x.pk: [x.nfworkflow_id, x.nfworkflow.repo] for x in Nfwfver.objects.all()}
    for x in NfConfigfile.objects.all():
        x.nfrepo_id, x.repolocation = ver_to_repo[x.nfpipe_id]
        x.save()
    for x in NfConfigfile.objects.all():
        if NfConfigfile.objects.filter(nfrepo=x.nfrepo, serverprofile=x.serverprofile).count() > 1:
            x.delete()

def fake(a, s):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0064_alter_psetcomponent_value'),
        ('rawstatus', '0044_analysisserverprofile_analysisoutshare_and_more'),
    ]

    operations = [
        # NfConfigfile to repo-server-config
        migrations.RemoveConstraint(
            model_name='nfconfigfile',
            name='uni_nfconfigfile',
        ),
        migrations.RenameField(
            model_name='nfconfigfile',
            old_name='nfconfig',
            new_name='configincluder',
        ),
        migrations.AddField(
            model_name='nfconfigfile',
            name='nfrepo',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='analysis.nextflowworkflowrepo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nfconfigfile',
            name='repolocation',
            field=models.TextField(default='', help_text='Usually a github repo, but if needed you can '
                'specify a path here'),
            preserve_default=False,
        ),

        migrations.RunPython(nfwfver_to_repo, fake),

        migrations.AddConstraint(
            model_name='nfconfigfile',
            constraint=models.UniqueConstraint(fields=('serverprofile', 'nfrepo'), name='uni_nfrepocfg'),
        ),
        migrations.RemoveField(
            model_name='nfconfigfile',
            name='nfpipe',
        ),
        migrations.RenameModel(
            old_name='NfConfigFile',
            new_name='NfRepoServerConfig',
        ),

        # New model only contains version commit of config to include
        migrations.CreateModel(
            name='NfConfigVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nfpipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.nextflowwfversionparamset')),
                ('nfservercfg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.nfreposerverconfig')),
                ('config_commit', models.CharField(max_length=50, help_text='Commit of version of config file for this pipeline on this server, will be passed to --config_commit')),
                ],
            options={
                'constraints': [models.UniqueConstraint(fields=('nfpipe', 'nfservercfg'), name='uni_nfserverpipe')],
                },
            ),

        migrations.AlterField(
            model_name='nextflowwfversionparamset',
            name='filename',
            field=models.TextField(help_text='Usually main.nf'),
        ),
    ]
