# Generated by Django 5.2 on 2026-07-29 07:41
import re
from collections import defaultdict

from django.db import migrations, models

# In its own migration file so the previous mig can add a field with an INDEX
# if this runs there then it cant CREATE INDEX because of pending triggers

def fake(a, s):
    pass


def fix_analysisfilevalue(a, s):
    # all 10000 afv -> adsi
    # all 180000 adsi -> afv
    DSA = a.get_model('analysis', 'DatasetAnalysis')
    AFV = a.get_model('analysis', 'AnalysisFileValue')
    ASV = a.get_model('analysis', 'AnalysisSetValue')
    ADSI = a.get_model('analysis', 'AnalysisDSInputFile')
    alldsa = {f'{x.dataset_id}__{x.analysis_id}': x for x in DSA.objects.all()}
    # Create ADSI for each file in the AFVs, add that to the AFVs
    for afv in AFV.objects.distinct('analysis', 'sfile_id').values('analysis_id', 'sfile_id'):
        try:
            dsa = DSA.objects.get(analysis_id=afv['analysis_id'], dataset__datasetrawfile__rawfile__storedfile__id=afv['sfile_id'])
        except DSA.DoesNotExist:
            # this happens when e.g. a file has changed dataset, the below only works if there is only one dset in the analysis
            # but we seem to be lucky and it works in our current DB
            dsa = DSA.objects.get(analysis_id=afv['analysis_id'])
        adsi = ADSI.objects.create(dsanalysis=dsa, sfile_id=afv['sfile_id'])
        AFV.objects.filter(analysis_id=afv['analysis_id'], sfile_id=afv['sfile_id']).update(adsfile=adsi)

    # Create AFV (with fraction) for each ADSI
    # Now we have analysisdatasetsetname, we can filter through that when doing ADSI
    # to create AFV for each, containing the fields/values (currently only regex!)
    # We add fractions manually (those were stored in the job data before, from the frontend)
    asvmap = defaultdict(dict)
    for x in ASV.objects.distinct('analysis', 'field').values('field', 'value', 'setname'):
        asvmap[x['setname']][x['field']] = x['value']
    for adsi in ADSI.objects.filter(dsanalysis__analysisdatasetsetname__isnull=False).values('pk', 'dsanalysis__analysisdatasetsetname__setname_id', 'sfile_id', 'dsanalysis__analysis_id', 'sfile__filename'):
        for field, asval in asvmap[adsi['dsanalysis__analysisdatasetsetname__setname_id']].items():
            if field == '__regex' and asval != '':
                try:
                    frac = re.match(asval, adsi['sfile__filename']).group(1)
                except (re.PatternError, AttributeError):
                    # User specified the regex wrong -> no fractions
                    pass
                except:
                    print(asval, adsi)
                    raise
                else:
                    AFV.objects.create(adsfile_id=adsi['pk'], field='__fraction', value=frac, sfile_id=adsi['sfile_id'], analysis_id=adsi['dsanalysis__analysis_id'])
            elif field[:2] != '__':
                AFV.objects.create(adsfile_id=adsi['pk'], field=field, value=asval, sfile_id=adsi['sfile_id'], analysis_id=adsi['dsanalysis__analysis_id'])
    
    # Remove ADSI duplicates:
    dups = [x for x in ADSI.objects.values('dsanalysis__analysis', 'sfile_id').annotate(c=models.Count('dsanalysis__analysis')).filter(c=2)]
    sfs = list( {x['sfile_id'] for x in dups})
    for ana in list({x['dsanalysis__analysis'] for x in dups}):
        ADSI.objects.filter(pk__in=[x.pk for x in ADSI.objects.filter(sfile_id__in=sfs, dsanalysis__analysis=ana).distinct('sfile_id')]).delete()



class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0066_anadsinputfile_setname_part1'),
        ('rawstatus', '0044_analysisserverprofile_analysisoutshare_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_analysisfilevalue, fake),
    ]
