# Generated by Django 5.2 on 2026-07-29 07:41

from django.db import migrations, models

# Last of three migrations, for removing obsolete fields and adding indexes

class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0067_remove_analysisdsinputfile_analysisset_and_more'),
        ('rawstatus', '0044_analysisserverprofile_analysisoutshare_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisfilevalue',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='analysisfilevalue',
            name='sfile',
        ),
        migrations.RemoveField(
            model_name='analysissetvalue',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='analysissetvalue',
            name='dataset',
        ),
        migrations.AlterField(
            model_name='psetcomponent',
            name='value',
            field=models.JSONField(default=dict, help_text='JSON, e.g. [path, instrument, set, plate] (path must be first),\n            {rawfile: __path, field_w_default: 1, file_type: "**function"}, empty_field: False},\n            {param: --oldmzmldef}, etc '),
        ),
        migrations.AddConstraint(
            model_name='analysisdatasetsetname',
            constraint=models.UniqueConstraint(fields=('setname', 'dsanalysis'), name='uni_dsana_setname'),
        ),
        migrations.AddConstraint(
            model_name='analysisdsinputfile',
            constraint=models.UniqueConstraint(fields=('dsanalysis', 'sfile'), name='uni_dsana_infile'),
        ),
        migrations.AddConstraint(
            model_name='analysisfilevalue',
            constraint=models.UniqueConstraint(fields=('adsfile', 'field'), name='uni_adsfile_fieldval'),
        ),
        migrations.AddConstraint(
            model_name='analysissetvalue',
            constraint=models.UniqueConstraint(fields=('setname', 'field'), name='uni_anasetfields'),
        ),
    ]
