# Generated by Django 4.2.13 on 2025-01-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_lineplotdata_plottype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineplotdata',
            name='shortname',
        ),
        migrations.RemoveField(
            model_name='boxplotdata',
            name='shortname',
        ),
        migrations.RemoveField(
            model_name='boxplotdata',
            name='lower',
        ),
        migrations.RemoveField(
            model_name='boxplotdata',
            name='upper',
        ),
    ]
