# Generated by Django 4.2.13 on 2025-02-13 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_lineplotdata_plottype_qcdata_runtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedPeptide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.TextField(unique=True)),
                ('charge', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TrackedPeptideSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.TextField()),
                ('acqmode', models.IntegerField(choices=[(1, 'DDA'), (2, 'DIA')])),
                ('active', models.BooleanField(default=True)),
                ('frozen', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PeptideTrackData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatype', models.IntegerField(choices=[(1, 'FWHM'), (2, 'Peptide MS1 area'), (3, 'Mass error'), (4, 'Retention time'), (5, 'Score'), (6, 'Ion mobility'), (7, 'Ion injection time(ms)'), (8, 'Amount MS2 peaks matched')])),
                ('value', models.FloatField()),
                ('peptide', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.trackedpeptide')),
                ('qcrun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.qcrun')),
            ],
        ),
        migrations.CreateModel(
            name='PeptideInSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peptide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.trackedpeptide')),
                ('peptideset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.trackedpeptideset')),
            ],
        ),
    ]
