---
# Tasks to only run once when you get a provisioned VM
# Installs packages, prepares directories.
# Upgrades packages

- hosts: storage
  remote_user: '{{ storage_connect_user }}'
  become: yes

  tasks:
    - name: Apt upgrade
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes

    - name: Install packages
      ansible.builtin.apt:
        pkg:
          - git
          - python3-venv
          - libpq-dev
          - python3-dev
          - build-essential
          - cifs-utils
          - docker.io
        state: present
            
    - name: Create kantele group
      ansible.builtin.group:
        name: "{{ kantelegroup }}"
        state: present

    - name: Create kantele user
      ansible.builtin.user:
        name: "{{ kanteleuser }}"
        group: "{{ kantelegroup }}"
        groups: docker
        create_home: yes
