# Generated by Django 5.2 on 2025-12-05 14:22

import datetime
from django.db import migrations, models
from kantele import settings


def fake(a, z):
    pass

def fix_close_log_level(ap, s):
    PL = ap.get_model('datasets', 'ProjectLog')
    PL.objects.filter(message__startswith='User ', message__endswith=' closed project'
            ).update(level=2)


def recalculate_seconds_to_minutes_bruker(ap, s):
    MT = ap.get_model('rawstatus', 'MSFileData')
    MT.objects.filter(rawfile__producer__msinstrument__filetype__name=settings.BRUKERRAW).update(
            mstime=models.F('mstime')/60)

class Migration(migrations.Migration):

    dependencies = [
        ('corefac', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepoptionprotocol',
            name='registered',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 12, 5, 14, 22, 16, 331780, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    
        migrations.RunPython(recalculate_seconds_to_minutes_bruker, fake),

        migrations.RunPython(fix_close_log_level, fake),

    ]
