# Generated by Django 5.2 on 2026-05-04 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corefac', '0004_prepoptionprotocol_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelineversion',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corefac.samplepipeline'),
        ),
    ]
