# Generated by Django 5.2 on 2026-02-20 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0062_alter_analysisdeleted_date'),
        ('datasets', '0026_alter_dataset_securityclass'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('shown', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DatasetMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgtype', models.IntegerField(choices=[(1, 'Delete Soon'), (2, 'Deleted'), (3, 'Files Arrived')])),
                ('dset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasets.dataset')),
                ('msg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.usermessage')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('dset', 'msgtype', 'msg'), name='uni_dsetmsg')],
            },
        ),
        migrations.CreateModel(
            name='AnalysisMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgtype', models.IntegerField(choices=[(1, 'Delete Soon'), (2, 'Deleted'), (3, 'Completed')])),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.analysis')),
                ('msg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.usermessage')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('analysis', 'msgtype'), name='uni_anamsg')],
            },
        ),
    ]
