# Generated by Django 4.2.13 on 2025-01-10 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rawstatus', '0031_remove_uploadtoken_is_library_uploadtoken_uploadtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSFileData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mstime', models.FloatField()),
                ('rawfile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rawstatus.rawfile')),
            ],
        ),
    ]
