# Generated by Django 4.2.13 on 2025-03-24 14:49

from django.db import migrations, models
import django.db.models.deletion
from django.db.models import F


def move_fields(a, s):
    SF = a.get_model('rawstatus', 'StoredFile')
    SFL = a.get_model('rawstatus', 'StoredFileLoc')
    SFL.objects.bulk_create(SFL(sfile=x, path=x.path, purged=x.purged, servershare=x.servershare) for x in SF.objects.all())


def fake(a, s):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('rawstatus', '0032_msfiledata'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredFileLoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawstatus.storedfile')),
                ('path', models.TextField()),
                ('purged', models.BooleanField(default=False)),
                ('servershare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawstatus.servershare')),
            ],
        ),
        migrations.AddField(
            model_name='servershare',
            name='max_security',
            field=models.IntegerField(choices=[(1, 'Not classified')], default=1),
            preserve_default=False,
        ),

        migrations.RunPython(move_fields, fake),

        migrations.RemoveConstraint(
            model_name='storedfile',
            name='uni_storedfile',
        ),

        migrations.AddConstraint(
            model_name='storedfileloc',
            constraint=models.UniqueConstraint(fields=('servershare', 'sfile'), name='uni_storedfile'),
        ),
    ]
