# Generated by Django 4.2.13 on 2025-04-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawstatus', '0033_storedfileservershare_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storedfile',
            name='path',
        ),
        migrations.RemoveField(
            model_name='storedfile',
            name='purged',
        ),
        migrations.RemoveField(
            model_name='storedfile',
            name='servershare',
        ),
    ]
