# Generated by Django 5.2 on 2025-07-03 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawstatus', '0035_servershare_active_servershare_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filejob',
            name='storedfile',
        ),
        migrations.RemoveField(
            model_name='servershare',
            name='server',
        ),
        migrations.RemoveField(
            model_name='servershare',
            name='share',
        ),
        migrations.RemoveField(
            model_name='uploadtoken',
            name='archive_only',
        ),
    ]
