# Generated by Django 5.2 on 2025-09-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawstatus', '0036_remove_filejob_storedfile_remove_servershare_server_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileserver',
            name='scratchdir',
            field=models.TextField(blank=True, help_text='For nextflow TMPDIR and stage if needed. Can be blank even for analysis servers'),
        ),
    ]
