# Generated by Django 5.2 on 2025-10-07 12:07

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import F


def move_to_asp(a, s):
    FS = a.get_model('rawstatus', 'FileServer')
    ASP = a.get_model('rawstatus', 'AnalysisServerProfile')
    for fs in FS.objects.filter(is_analysis=True):
        # nfprofiles are from nfworkflowparamset, so will differ per wf, do by hand
        ASP.objects.create(server=fs, nfprofiles=[], scratchdir=fs.scratchdir, queue_name=fs.name)


def back_to_fs(a, s):
    FS = a.get_model('rawstatus', 'FileServer')
    ASP = a.get_model('rawstatus', 'AnalysisServerProfile')
    for asp in ASP.objects.all():
        fs = asp.server
        fs.is_analysis=True
        fs.scratchdir=asp.scratchdir
        fs.name=asp.queue_name
        fs.save()


class Migration(migrations.Migration):

    dependencies = [
        ('rawstatus', '0037_alter_fileserver_scratchdir'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisServerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nfprofiles', models.JSONField(default=list)),
                ('scratchdir', models.TextField(blank=True, help_text='For nextflow TMPDIR and stage if needed. Can be blank if not needed')),
                ('queue_name', models.TextField(unique=True)),
                ('server', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rawstatus.fileserver')),
            ],
        ),
        migrations.RunPython(move_to_asp, back_to_fs),

        migrations.AlterField(
            model_name='servershare',
            name='max_security',
            field=models.IntegerField(choices=[(1, 'Open')]),
        ),
    ]
