# Generated by Django 5.2 on 2025-10-07 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rawstatus', '0038_analysisserverprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileserver',
            name='is_analysis',
        ),
        migrations.RemoveField(
            model_name='fileserver',
            name='scratchdir',
        ),
        migrations.RemoveField(
            model_name='servershare',
            name='has_rawdata',
        ),
    ]
