# Generated by Django 5.2 on 2025-10-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawstatus', '0039_remove_fileserver_is_analysis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servershare',
            name='max_security',
            field=models.IntegerField(choices=[(1, 'Accessible')]),
        ),
    ]
