# Generated by Django 5.2 on 2025-11-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawstatus', '0040_alter_servershare_max_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='msfiledata',
            name='errmsg',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='msfiledata',
            name='success',
            field=models.BooleanField(default=True),
        ),
    ]
