# Generated by Django 5.2 on 2026-01-13 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rawstatus', '0041_msfiledata_errmsg_msfiledata_success'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisserverprofile',
            name='nfprofiles',
        ),
    ]
