# Generated by Django 5.2 on 2026-04-22 13:23

import django.db.models.deletion
from django.db import migrations, models

from rawstatus import models as rm


def set_anaoutshare(apps, s):
    ASP = apps.get_model('rawstatus', 'AnalysisServerProfile')    
    for asp in ASP.objects.all():
        asp.name = asp.server.name
        asp.analysisoutshare = asp.server.fileservershare_set.filter(share__function=rm.ShareFunction.ANALYSISRESULTS).get()
        asp.save()

def fake(apps, s):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('rawstatus', '0043_seconds_to_minutes_bruker_mstime'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisserverprofile',
            name='analysisoutshare',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rawstatus.fileservershare'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysisserverprofile',
            name='name',
            field=models.TextField(default='a', help_text='E.g. server/project name'),
            preserve_default=False,
        ),
        migrations.RunPython(set_anaoutshare, fake),

        migrations.AddField(
            model_name='analysisserverprofile',
            name='nfparams',
            field=models.JSONField(blank=True, default=list, help_text='List of parameters to pass for this server/project, e.g. ["--project", "proj12345"]'),
        ),
        migrations.AlterField(
            model_name='analysisserverprofile',
            name='queue_name',
            field=models.TextField(help_text='Also identifier for which project on HPC'),
        ),
        migrations.AlterField(
            model_name='analysisserverprofile',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawstatus.fileserver'),
        ),
        migrations.AlterField(
            model_name='analysisserverprofile',
            name='name',
            field=models.TextField(help_text='E.g. server/project name', unique=True),
        ),
    ]
